'use client'

// import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { SessionProvider } from "next-auth/react";

import "./globals.css";

//This is the MAIN font currently
const robotoSans = Roboto({ 
  weight:"300",
  style:"normal",
  subsets:["latin"]
});


// export const metadata: Metadata = {
//   title: "Ideal Strategies",
//   description: "Generated by create next app", // edit
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${robotoSans.className} antialiased min-h-screen flex flex-col pt-16 bg-gray-900`}>
        <SessionProvider>{children}</SessionProvider>
      </body>
    </html>
  );
};
